spring:
  application:
    name: desafio
#DB
  datasource:
    url: jdbc:postgresql://localhost:5432/desafio
    #    url: jdbc:postgresql://db:5432/assistent?createDatabaseIfNotExist=true&useSSL=false #docker
    username: guiborges
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect